type AlmedEvent = {
    id: string,
    title: string,
    organiser: string,
    date: ?string,
    endDate: ?string,
    type: string,
    subject: string,
    language: string,
    location: string,
    locationDescription: string,
    description: string,
    latitude: number,
    longitude: number,
    participants: Array<{
        name: string,
        title: string,
        company: string,
    }>,
    green: boolean,
    availabilty: string,
    live: boolean,
    food: boolean,
    web: string,
    url: string,
}