// flow-typed signature: 4b9416b59ddf6815947ada31b6cff81e
// flow-typed version: <<STUB>>/passport-facebook-token_v^3.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-facebook-token'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-facebook-token' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-facebook-token/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-facebook-token/lib/index.js' {
  declare module.exports: $Exports<'passport-facebook-token/lib/index'>;
}
